/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: basedef.proto */

#ifndef PROTOBUF_C_basedef_2eproto__INCLUDED
#define PROTOBUF_C_basedef_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CIntegers CIntegers;
typedef struct _CFloats CFloats;


/* --- enums --- */


/* --- messages --- */

struct  _CIntegers
{
  ProtobufCMessage base;
  protobuf_c_boolean has_int32_v;
  int32_t int32_v;
  protobuf_c_boolean has_int64_v;
  int64_t int64_v;
  protobuf_c_boolean has_uint32_v;
  uint32_t uint32_v;
  protobuf_c_boolean has_uint64_v;
  uint64_t uint64_v;
  protobuf_c_boolean has_int16_v;
  int32_t int16_v;
  protobuf_c_boolean has_uint16_v;
  uint32_t uint16_v;
  protobuf_c_boolean has_char_byte;
  uint32_t char_byte;
};
#define CINTEGERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cintegers__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0u }


struct  _CFloats
{
  ProtobufCMessage base;
  protobuf_c_boolean has_float32;
  float float32;
  protobuf_c_boolean has_float64;
  double float64;
};
#define CFLOATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfloats__descriptor) \
    , 0,0, 0,0 }


/* CIntegers methods */
void   cintegers__init
                     (CIntegers         *message);
size_t cintegers__get_packed_size
                     (const CIntegers   *message);
size_t cintegers__pack
                     (const CIntegers   *message,
                      uint8_t             *out);
size_t cintegers__pack_to_buffer
                     (const CIntegers   *message,
                      ProtobufCBuffer     *buffer);
CIntegers *
       cintegers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cintegers__free_unpacked
                     (CIntegers *message,
                      ProtobufCAllocator *allocator);
/* CFloats methods */
void   cfloats__init
                     (CFloats         *message);
size_t cfloats__get_packed_size
                     (const CFloats   *message);
size_t cfloats__pack
                     (const CFloats   *message,
                      uint8_t             *out);
size_t cfloats__pack_to_buffer
                     (const CFloats   *message,
                      ProtobufCBuffer     *buffer);
CFloats *
       cfloats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfloats__free_unpacked
                     (CFloats *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CIntegers_Closure)
                 (const CIntegers *message,
                  void *closure_data);
typedef void (*CFloats_Closure)
                 (const CFloats *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cintegers__descriptor;
extern const ProtobufCMessageDescriptor cfloats__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_basedef_2eproto__INCLUDED */
