/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: basedef.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "basedef.pb-c.h"
void   cintegers__init
                     (CIntegers         *message)
{
  static CIntegers init_value = CINTEGERS__INIT;
  *message = init_value;
}
size_t cintegers__get_packed_size
                     (const CIntegers *message)
{
  assert(message->base.descriptor == &cintegers__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cintegers__pack
                     (const CIntegers *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cintegers__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cintegers__pack_to_buffer
                     (const CIntegers *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cintegers__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CIntegers *
       cintegers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CIntegers *)
     protobuf_c_message_unpack (&cintegers__descriptor,
                                allocator, len, data);
}
void   cintegers__free_unpacked
                     (CIntegers *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cintegers__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cfloats__init
                     (CFloats         *message)
{
  static CFloats init_value = CFLOATS__INIT;
  *message = init_value;
}
size_t cfloats__get_packed_size
                     (const CFloats *message)
{
  assert(message->base.descriptor == &cfloats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfloats__pack
                     (const CFloats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cfloats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfloats__pack_to_buffer
                     (const CFloats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cfloats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFloats *
       cfloats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFloats *)
     protobuf_c_message_unpack (&cfloats__descriptor,
                                allocator, len, data);
}
void   cfloats__free_unpacked
                     (CFloats *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cfloats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t cintegers__char_byte__default_value = 0u;
static const ProtobufCFieldDescriptor cintegers__field_descriptors[7] =
{
  {
    "int32_v",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CIntegers, has_int32_v),
    offsetof(CIntegers, int32_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int64_v",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(CIntegers, has_int64_v),
    offsetof(CIntegers, int64_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uint32_v",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CIntegers, has_uint32_v),
    offsetof(CIntegers, uint32_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uint64_v",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CIntegers, has_uint64_v),
    offsetof(CIntegers, uint64_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int16_v",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(CIntegers, has_int16_v),
    offsetof(CIntegers, int16_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uint16_v",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CIntegers, has_uint16_v),
    offsetof(CIntegers, uint16_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "char_byte",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CIntegers, has_char_byte),
    offsetof(CIntegers, char_byte),
    NULL,
    &cintegers__char_byte__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cintegers__field_indices_by_name[] = {
  6,   /* field[6] = char_byte */
  4,   /* field[4] = int16_v */
  0,   /* field[0] = int32_v */
  1,   /* field[1] = int64_v */
  5,   /* field[5] = uint16_v */
  2,   /* field[2] = uint32_v */
  3,   /* field[3] = uint64_v */
};
static const ProtobufCIntRange cintegers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cintegers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CIntegers",
  "CIntegers",
  "CIntegers",
  "",
  sizeof(CIntegers),
  7,
  cintegers__field_descriptors,
  cintegers__field_indices_by_name,
  1,  cintegers__number_ranges,
  (ProtobufCMessageInit) cintegers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cfloats__field_descriptors[2] =
{
  {
    "float32",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(CFloats, has_float32),
    offsetof(CFloats, float32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float64",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(CFloats, has_float64),
    offsetof(CFloats, float64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfloats__field_indices_by_name[] = {
  0,   /* field[0] = float32 */
  1,   /* field[1] = float64 */
};
static const ProtobufCIntRange cfloats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cfloats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CFloats",
  "CFloats",
  "CFloats",
  "",
  sizeof(CFloats),
  2,
  cfloats__field_descriptors,
  cfloats__field_indices_by_name,
  1,  cfloats__number_ranges,
  (ProtobufCMessageInit) cfloats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
