/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgtest.proto */

#ifndef PROTOBUF_C_msgtest_2eproto__INCLUDED
#define PROTOBUF_C_msgtest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Role Role;
typedef struct _Family Family;
typedef struct _ChatMsg ChatMsg;


/* --- enums --- */


/* --- messages --- */

struct  _Role
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  int32_t id;
  char *name;
  protobuf_c_boolean has_money;
  int32_t money;
  size_t n_tasks;
  int32_t *tasks;
};
extern char role__name__default_value[];
#define ROLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&role__descriptor) \
    , 0,0, role__name__default_value, 0,0, 0,NULL }


struct  _Family
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_lv;
  int32_t lv;
  size_t n_roles;
  Role **roles;
};
extern char family__name__default_value[];
#define FAMILY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&family__descriptor) \
    , family__name__default_value, 0,0, 0,NULL }


struct  _ChatMsg
{
  ProtobufCMessage base;
  char *msg;
};
extern char chat_msg__msg__default_value[];
#define CHAT_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_msg__descriptor) \
    , chat_msg__msg__default_value }


/* Role methods */
void   role__init
                     (Role         *message);
size_t role__get_packed_size
                     (const Role   *message);
size_t role__pack
                     (const Role   *message,
                      uint8_t             *out);
size_t role__pack_to_buffer
                     (const Role   *message,
                      ProtobufCBuffer     *buffer);
Role *
       role__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   role__free_unpacked
                     (Role *message,
                      ProtobufCAllocator *allocator);
/* Family methods */
void   family__init
                     (Family         *message);
size_t family__get_packed_size
                     (const Family   *message);
size_t family__pack
                     (const Family   *message,
                      uint8_t             *out);
size_t family__pack_to_buffer
                     (const Family   *message,
                      ProtobufCBuffer     *buffer);
Family *
       family__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   family__free_unpacked
                     (Family *message,
                      ProtobufCAllocator *allocator);
/* ChatMsg methods */
void   chat_msg__init
                     (ChatMsg         *message);
size_t chat_msg__get_packed_size
                     (const ChatMsg   *message);
size_t chat_msg__pack
                     (const ChatMsg   *message,
                      uint8_t             *out);
size_t chat_msg__pack_to_buffer
                     (const ChatMsg   *message,
                      ProtobufCBuffer     *buffer);
ChatMsg *
       chat_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_msg__free_unpacked
                     (ChatMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Role_Closure)
                 (const Role *message,
                  void *closure_data);
typedef void (*Family_Closure)
                 (const Family *message,
                  void *closure_data);
typedef void (*ChatMsg_Closure)
                 (const ChatMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor role__descriptor;
extern const ProtobufCMessageDescriptor family__descriptor;
extern const ProtobufCMessageDescriptor chat_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msgtest_2eproto__INCLUDED */
