/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msgtest.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msgtest.pb-c.h"
void   role__init
                     (Role         *message)
{
  static Role init_value = ROLE__INIT;
  *message = init_value;
}
size_t role__get_packed_size
                     (const Role *message)
{
  assert(message->base.descriptor == &role__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t role__pack
                     (const Role *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &role__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t role__pack_to_buffer
                     (const Role *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &role__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Role *
       role__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Role *)
     protobuf_c_message_unpack (&role__descriptor,
                                allocator, len, data);
}
void   role__free_unpacked
                     (Role *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &role__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   family__init
                     (Family         *message)
{
  static Family init_value = FAMILY__INIT;
  *message = init_value;
}
size_t family__get_packed_size
                     (const Family *message)
{
  assert(message->base.descriptor == &family__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t family__pack
                     (const Family *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &family__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t family__pack_to_buffer
                     (const Family *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &family__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Family *
       family__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Family *)
     protobuf_c_message_unpack (&family__descriptor,
                                allocator, len, data);
}
void   family__free_unpacked
                     (Family *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &family__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_msg__init
                     (ChatMsg         *message)
{
  static ChatMsg init_value = CHAT_MSG__INIT;
  *message = init_value;
}
size_t chat_msg__get_packed_size
                     (const ChatMsg *message)
{
  assert(message->base.descriptor == &chat_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_msg__pack
                     (const ChatMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_msg__pack_to_buffer
                     (const ChatMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatMsg *
       chat_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatMsg *)
     protobuf_c_message_unpack (&chat_msg__descriptor,
                                allocator, len, data);
}
void   chat_msg__free_unpacked
                     (ChatMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &chat_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char role__name__default_value[] = "";
static const int32_t role__id__default_value = 0;
static const int32_t role__money__default_value = 0;
static const ProtobufCFieldDescriptor role__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Role, has_id),
    offsetof(Role, id),
    NULL,
    &role__id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Role, name),
    NULL,
    &role__name__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "money",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Role, has_money),
    offsetof(Role, money),
    NULL,
    &role__money__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tasks",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Role, n_tasks),
    offsetof(Role, tasks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned role__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = money */
  1,   /* field[1] = name */
  3,   /* field[3] = tasks */
};
static const ProtobufCIntRange role__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor role__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Role",
  "Role",
  "Role",
  "",
  sizeof(Role),
  4,
  role__field_descriptors,
  role__field_indices_by_name,
  1,  role__number_ranges,
  (ProtobufCMessageInit) role__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char family__name__default_value[] = "";
static const int32_t family__lv__default_value = 0;
static const ProtobufCFieldDescriptor family__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Family, name),
    NULL,
    &family__name__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Family, has_lv),
    offsetof(Family, lv),
    NULL,
    &family__lv__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roles",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Family, n_roles),
    offsetof(Family, roles),
    &role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned family__field_indices_by_name[] = {
  1,   /* field[1] = lv */
  0,   /* field[0] = name */
  2,   /* field[2] = roles */
};
static const ProtobufCIntRange family__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor family__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Family",
  "Family",
  "Family",
  "",
  sizeof(Family),
  3,
  family__field_descriptors,
  family__field_indices_by_name,
  1,  family__number_ranges,
  (ProtobufCMessageInit) family__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char chat_msg__msg__default_value[] = "";
static const ProtobufCFieldDescriptor chat_msg__field_descriptors[1] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatMsg, msg),
    NULL,
    &chat_msg__msg__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_msg__field_indices_by_name[] = {
  0,   /* field[0] = msg */
};
static const ProtobufCIntRange chat_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chat_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChatMsg",
  "ChatMsg",
  "ChatMsg",
  "",
  sizeof(ChatMsg),
  1,
  chat_msg__field_descriptors,
  chat_msg__field_indices_by_name,
  1,  chat_msg__number_ranges,
  (ProtobufCMessageInit) chat_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
