/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netpub.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "netpub.pb-c.h"
void   msg_head__init
                     (MsgHead         *message)
{
  static MsgHead init_value = MSG_HEAD__INIT;
  *message = init_value;
}
size_t msg_head__get_packed_size
                     (const MsgHead *message)
{
  assert(message->base.descriptor == &msg_head__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_head__pack
                     (const MsgHead *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_head__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_head__pack_to_buffer
                     (const MsgHead *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_head__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgHead *
       msg_head__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgHead *)
     protobuf_c_message_unpack (&msg_head__descriptor,
                                allocator, len, data);
}
void   msg_head__free_unpacked
                     (MsgHead *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &msg_head__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mq_head__init
                     (MqHead         *message)
{
  static MqHead init_value = MQ_HEAD__INIT;
  *message = init_value;
}
size_t mq_head__get_packed_size
                     (const MqHead *message)
{
  assert(message->base.descriptor == &mq_head__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mq_head__pack
                     (const MqHead *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mq_head__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mq_head__pack_to_buffer
                     (const MqHead *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mq_head__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MqHead *
       mq_head__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MqHead *)
     protobuf_c_message_unpack (&mq_head__descriptor,
                                allocator, len, data);
}
void   mq_head__free_unpacked
                     (MqHead *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mq_head__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rmi_head__init
                     (RmiHead         *message)
{
  static RmiHead init_value = RMI_HEAD__INIT;
  *message = init_value;
}
size_t rmi_head__get_packed_size
                     (const RmiHead *message)
{
  assert(message->base.descriptor == &rmi_head__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmi_head__pack
                     (const RmiHead *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rmi_head__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmi_head__pack_to_buffer
                     (const RmiHead *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rmi_head__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmiHead *
       rmi_head__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmiHead *)
     protobuf_c_message_unpack (&rmi_head__descriptor,
                                allocator, len, data);
}
void   rmi_head__free_unpacked
                     (RmiHead *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rmi_head__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const int32_t msg_head__flag__default_value = 0;
static const int32_t msg_head__size__default_value = 0;
static const int32_t msg_head__msgtype__default_value = 0;
static const ProtobufCFieldDescriptor msg_head__field_descriptors[3] =
{
  {
    "flag",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MsgHead, has_flag),
    offsetof(MsgHead, flag),
    NULL,
    &msg_head__flag__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MsgHead, has_size),
    offsetof(MsgHead, size),
    NULL,
    &msg_head__size__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgtype",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MsgHead, has_msgtype),
    offsetof(MsgHead, msgtype),
    NULL,
    &msg_head__msgtype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_head__field_indices_by_name[] = {
  0,   /* field[0] = flag */
  2,   /* field[2] = msgtype */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange msg_head__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor msg_head__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MsgHead",
  "MsgHead",
  "MsgHead",
  "",
  sizeof(MsgHead),
  3,
  msg_head__field_descriptors,
  msg_head__field_indices_by_name,
  1,  msg_head__number_ranges,
  (ProtobufCMessageInit) msg_head__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t mq_head__commond__default_value = 0;
static const int32_t mq_head__toid__default_value = 0;
static const ProtobufCFieldDescriptor mq_head__field_descriptors[2] =
{
  {
    "commond",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MqHead, has_commond),
    offsetof(MqHead, commond),
    NULL,
    &mq_head__commond__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MqHead, has_toid),
    offsetof(MqHead, toid),
    NULL,
    &mq_head__toid__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mq_head__field_indices_by_name[] = {
  0,   /* field[0] = commond */
  1,   /* field[1] = toid */
};
static const ProtobufCIntRange mq_head__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mq_head__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MqHead",
  "MqHead",
  "MqHead",
  "",
  sizeof(MqHead),
  2,
  mq_head__field_descriptors,
  mq_head__field_indices_by_name,
  1,  mq_head__number_ranges,
  (ProtobufCMessageInit) mq_head__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char rmi_head__identity__default_value[] = "";
static const int32_t rmi_head__msgid__default_value = 0;
static const ProtobufCFieldDescriptor rmi_head__field_descriptors[2] =
{
  {
    "msgid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RmiHead, has_msgid),
    offsetof(RmiHead, msgid),
    NULL,
    &rmi_head__msgid__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identity",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RmiHead, identity),
    NULL,
    &rmi_head__identity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rmi_head__field_indices_by_name[] = {
  1,   /* field[1] = identity */
  0,   /* field[0] = msgid */
};
static const ProtobufCIntRange rmi_head__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rmi_head__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RmiHead",
  "RmiHead",
  "RmiHead",
  "",
  sizeof(RmiHead),
  2,
  rmi_head__field_descriptors,
  rmi_head__field_indices_by_name,
  1,  rmi_head__number_ranges,
  (ProtobufCMessageInit) rmi_head__init,
  NULL,NULL,NULL    /* reserved[123] */
};
